-- The schema Hibernate generated with ddl-auto: update (taken from pg_dump of a running database), now owned by
-- Flyway. Hibernate only validates it from here on (ddl-auto: validate), so a change to an entity needs a new
-- migration, never an edit to this file: Flyway checksums applied migrations and refuses to start if one changes.

CREATE TABLE product (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255),
    price_cents bigint  NOT NULL,
    stock       integer NOT NULL
);

CREATE TABLE cart_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    varchar(255),
    product_id bigint,
    quantity   integer NOT NULL
);
CREATE INDEX cart_items_cart_id_idx ON cart_items (cart_id);

CREATE TABLE orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     varchar(255),
    created_at  timestamp(6) with time zone,
    status      varchar(255) CONSTRAINT orders_status_check CHECK (status IN ('PENDING', 'PAID', 'FAILED')),
    total_cents bigint NOT NULL
);

CREATE TABLE order_lines (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   bigint,
    product_id bigint,
    quantity   integer NOT NULL
);
CREATE INDEX order_lines_order_id_idx ON order_lines (order_id);
